### ISSUE TITLE
Wrong escape masks for escape value on simd bounds (DMD)

### ISSUE THREAD

**Issue by gizmomogwai** [libmir/mir-ion#172]
Cannot parse this snippet from the dub registry:

dub-registry.snippet:
```
[{
	"_id": "4fb7e8c98e61838659000000",
	"owner": "4fb7e76ac2f9e3834c000000",
	"name": "vibenews",
	"repository": {
		"kind": "github",
		"owner": "rejectedsoftware",
		"project": "vibenews"
	},
	"versions": [
		{
			"date": "2020-10-27T20:26:36Z",
			"version": "~master",
			"commitID": "13a5086acf405f44e4d5975148b9313274c16fc7",
			"info": {"packageDescriptionFile":"dub.sdl","authors":["Sönke Ludwig"],"license":"AGPL-3.0","copyright":"Copyright (c) 2012-2018 Sönke Ludwig","name":"vibenews","description":"Combined web forum and NNTP server implementation for stand-alone newsgroups","homepage":"https://github.com/rejectedsoftware/vibenews","dependencies":{"vibe-d":">=0.8.0 <0.10.0-0","antispam":"~>0.1.2","userman":"~>0.4.0"}},
			"readme": "vibenews\n========\n\nNNTP server/web forum implementation for stand-alone newsgroups\n\nSee <https://forum.rejectedsoftware.com/> for a running version.\n\n[![Build Status](https://travis-ci.org/rejectedsoftware/vibenews.svg?branch=master)](https://travis-ci.org/rejectedsoftware/vibenews)\n\nFeatures\n--------\n\n - Acts as newsgroup server (NNTP)\n - Acts as a web forum\n - Lightning fast\n - Supports access restriction for individual groups\n - The web forum allows github style markdown formatting\n - Mobile friendly default layout with gravatar integration\n\n\nInstallation\n------------\n\n1. Install [dub](https://github.com/rejectedsoftware/dub/) and [MongoDB](http://www.mongodb.org/).\n\n2. Clone the project\n\n        git clone git://github.com/rejectedsoftware/vibenews.git\n    \n3. Compile and run\n\n        cd vibenews\n        dub\n\nThe following ports are now available, per the default `settings.json` file:\n\n - :119 provides the NNTP interface\n - 127.0.0.1:8009 provides the HTTP web interface\n - 127.0.0.1:9009 provides the admin interface\n\nYou can leave these settings unchanged if you use a reverse proxy to make the web forum available to the public. Alternatively, you change the settings file to make the web forum directly reachable from the Internet. You can delete the key `webBindAddresses` to listen on the default network interfaces or you can provide your own list of bind addresses.\n\nExample `settings.json`:\n\n```\n{\n\t\"title\": \"Example Forum\",\n\t\"host\": \"forum.example.org\",\n\t\"nntpPort\n",
			"readmeMarkdown": true,
			"docFolder": ""
		}
	],
	"stats": {
		"updatedAt": "2021-05-15T17:56:46.025Z",
		"downloads": {
			"total": 0,
			"monthly": 0,
			"weekly": 0,
			"daily": 0
		},
		"repo": {
			"stars": 1,
			"watchers": 0,
			"forks": 0,
			"issues": 0
		},
		"score": 0.06067143753170967
	},
	"errors": [],
	"categories": [
		"application.desktop.development"
	],
	"updateCounter": 2,
	"logo": "609ee3a58c10971b2e837fd2",
	"documentationURL": "",
	"textScore": 0
}]
```

test.d:
```
#!/usr/bin/env dub
/+ dub.sdl:
dependency "mir-ion" version="~>0.1.18"
+/

import std;
import mir.ion.deser.json;

void main()
{
    struct Package {
        string name;
    }

    writeln(readText("dub-registry.snippet").deserializeJson!(Package[]));
}
```

output:
```
core.exception.AssertError@../../../../../.dub/packages/mir-ion-0.1.18/mir-ion/source/mir/ion/internal/stage3.d(255): s
----------------
??:? _d_assert_msg [0x105554a9e]
/Users/christiankoestlin/dlang/dmd-2.096.1/osx/bin/../../src/phobos/std/typecons.d:874 pure nothrow @nogc @trusted void mir.ion.internal.stage3.stage3!(mir.ion.internal.stage4_s.singleThreadJsonImpl!(4096uL, mir.ion.internal.stage4_s.singleThreadJsonText!(4096u, immutable(mir.string_table.MirStringTable!(1uL, 4uL, false, char).MirStringTable), mir.ion.internal.data_holder.IonTapeHolder!(32768uL).IonTapeHolder).singleThreadJsonText(ref immutable(mir.string_table.MirStringTable!(1uL, 4uL, false, char).MirStringTable), ref mir.ion.internal.data_holder.IonTapeHolder!(32768uL).IonTapeHolder, scope const(char)[]).__lambda4(scope char*, ref long, ref bool), immutable(mir.string_table.MirStringTable!(1uL, 4uL, false, char).MirStringTable), mir.ion.internal.data_holder.IonTapeHolder!(32768uL).IonTapeHolder).singleThreadJsonImpl(ref immutable(mir.string_table.MirStringTable!(1uL, 4uL, false, char).MirStringTable), ref mir.ion.internal.data_holder.IonTapeHolder!(32768uL).IonTapeHolder).__lambda10(), immutable(mir.string_table.MirStringTable!(1uL, 4uL, false, char).MirStringTable)).stage3(ref mir.ion.internal.stage3.Stage3State, ref immutable(mir.string_table.MirStringTable!(1uL, 4uL, false, char).MirStringTable)) [0x10552dfba]
```

**Comment by 9il** [comment]
reduced test
```d
    static immutable text = q{"n2. Clone theproject_n_n        git clone git://github.com/rej\n2. Clone the project_n_n        git clone git://github.com/rejn"};
    import mir.ion.deser.json;
    import std.stdio;
    writeln(text.deserializeJson!(string));

```

**Comment by 9il** [comment]
It is DMD only issue

**Comment by 9il** [comment]
Fixed in 0.1.19

**Comment by gizmomogwai** [comment]
Wow .. that was fast. Unfortunately for me parsing the complete dub registry is still broken. I attached here a small standalone snippet, because this time I could not reduce the input :(

test.d:
```
#!/usr/bin/env dub
/+ dub.sdl:
dependency "mir-ion" version="~>0.1.19"
dependency "requests" version="~>2.0.0"
dependency "asdf" version="~>0.7.8"
+/

import std;
import mir.ion.deser.json;
import asdf;
import requests;

void main()
{
    struct Package {
        string name;
    }

    const path = "dub-registry.cache";
    if (!path.exists)
    {
        const url = "https://code.dlang.org/api/packages/dump";
        "Downloading %s to %s".format(url, path).writeln;
        std.file.write(path, url.getContent.data);
    }

    import std.datetime.stopwatch;
    auto sw = StopWatch(AutoStart.yes);

    {
        sw.reset;
        auto result = path.readText.parseJSON;
        writeln("parsing with parseJSON: ", sw.peek);
    }

    {
        sw.reset;
        auto result = path.readText.deserialize!(Package[]);
        writeln("parsing with asdf: ", sw.peek);
    }

    {
        sw.reset;
        writeln(path.readText.deserializeJson!(Package[]));
        writeln("parsing with mir-ion: ", sw.peek);
    }
}
```

I switched now to asdf, but would still like to switch back to mir-ion if possible. Btw, concratulation on both of the libraries, they are really fast!

**Comment by gizmomogwai** [comment]
sorry .. forgot the output:
```
 ./test.d 
parsing with parseJSON: 5 secs, 542 ms, 690 μs, and 9 hnsecs
parsing with asdf: 971 ms, 310 μs, and 7 hnsecs
mir.serde.SerdeMirException@../../../../.dub/packages/mir-ion-0.1.19/mir-ion/source/mir/ion/deser/json.d(47): unexpected JSON value. location = 290818, last input key = ?[![Bu
----------------
/Users/christiankoestlin/dlang/dmd-2.096.1/osx/bin/../../src/phobos/std/typecons.d:1255 pure @trusted void mir.ion.deser.json.deserializeJsonImpl!(false).deserializeJsonImpl!(test.main().Package[]).deserializeJsonImpl(scope const(char)[]).__lambda7() [0x10c685dab]
/Users/christiankoestlin/dlang/dmd-2.096.1/osx/bin/../../src/phobos/std/typecons.d:1255 pure @safe test.main().Package[] mir.ion.deser.json.deserializeJsonImpl!(false).deserializeJsonImpl!(test.main().Package[]).deserializeJsonImpl(scope const(char)[]) [0x10c685cd5]
test.d:44 _Dmain [0x10c67603a]
Program exited with code 1
```

**Comment by 9il** [comment]
@gizmomogwai Thank you for the bug reports. Fixed in v0.1.20. Should pass now.

**Comment by gizmomogwai** [comment]
Thanks again for the fast fix. Works for me now. 🛠️ 
asdf still beats mir-ion on my machine: 🐎 
```
./test.d
parsing with parseJSON: 5 secs, 622 ms, 663 μs, and 7 hnsecs
parsing with asdf: 961 ms, 634 μs, and 5 hnsecs
parsing with mir-ion: 1 sec, 528 ms, 511 μs, and 9 hnsecs
```
this library is black art btw. from the diff i would not even say that this is json parsing :) 🧙

**Comment by 9il** [comment]
It is possible, because Mir Ion will move more data to compress its DOM. BTW, you can parse directly from file using deserialiseJsonFile, it will not allocate memo for the whole file then. How did you compile the code (dub command)?

**Comment by gizmomogwai** [comment]
just chmod u+x and run it (in linux) with ./test.d. dub needs to be in the path ... also i do not know how to add compiler flags there .. otherwise we can remove the header and just do normal ldc or dmd ...

**Comment by gizmomogwai** [comment]
I just tested again with ldc2
```
(ldc-1.26.0)myname@my-machine ~/S/p/_/active (master)> dub test.d --build=release
parsing with parseJSON: 4 secs, 705 ms, 454 μs, and 4 hnsecs
parsing with asdf: 797 ms, 584 μs, and 3 hnsecs
parsing with mir-ion: 681 ms and 185 μs
```
